In [0]:
from pandas import read_csv
from keras.models import Sequential
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
# calculate accuracy measures and confusion matrix
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
%matplotlib inline

1. Read the dataset

In [98]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
df  = pd.read_csv('/content/drive/My Drive/Colab Notebooks/bank.csv') 

In [100]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [101]:
df.shape

(10000, 14)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


2. Drop the columns which are unique for all users like IDs (5 points)

In [0]:
X = df.iloc[:, 3:13].values
y = df.iloc[:,13].values

In [104]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

3. Distinguish the feature and target set (5 points)

In [0]:
# We have created X & y varaiables on the above steps.

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [107]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


4. Divide the data set into Train and test sets

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

5. Normalize the train and test data (5 points)

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

6. Initialize & build the model (10 points)

In [0]:
# Building a Model
classifier = Sequential()
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [0]:
# Compiling the Model
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [112]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 3s 402us/step - loss: 0.4840 - acc: 0.7962
Epoch 2/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.4258 - acc: 0.7967
Epoch 3/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.4180 - acc: 0.8140
Epoch 4/100
8000/8000 [==============================] - 3s 338us/step - loss: 0.4121 - acc: 0.8291
Epoch 5/100
8000/8000 [==============================] - 3s 348us/step - loss: 0.4074 - acc: 0.8347
Epoch 6/100
8000/8000 [==============================] - 3s 342us/step - loss: 0.4035 - acc: 0.8361
Epoch 7/100
8000/8000 [==============================] - 3s 338us/step - loss: 0.4018 - acc: 0.8349
Epoch 8/100
8000/8000 [==============================] - 3s 349us/step - loss: 0.4003 - acc: 0.8367
Epoch 9/100
8000/8000 [==============================] - 3s 350us/step - loss: 0.3988 - acc: 0.8367
Epoch 10/100
8000/8000 [==============================] - 3s 350us/step - loss: 0.3974 - acc: 0.8375

8. Predict the results using 0.5 as a threshold (Optional)

In [113]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

9. Print the Accuracy score and confusion matrix (5 points)

In [114]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1534,   55],
       [ 269,  142]])

In [115]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
accuracy

0.838

7. Optimize the model (Optional)

In [0]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.2, random_state=7)

In [0]:
from keras.utils import np_utils

In [0]:
Y_train=np_utils.to_categorical(y_train1)
Y_test=np_utils.to_categorical(y_test1)

In [119]:
y_test.shape

(2000,)

In [0]:
X_train=np.expand_dims(X_train1,axis=2)
X_test=np.expand_dims(X_test1,axis=2)

In [121]:
X_train.shape

(8000, 11, 1)

In [122]:
X_train.shape[1]

11

In [0]:
model1 = Sequential()
model1.add(Conv1D(filters=2,kernel_size=3,input_shape=(X_train.shape[1],X_train.shape[2]),padding='same',activation='relu'))
model1.add(MaxPooling1D(pool_size=2))
model1.add(Flatten())
model1.add(Dense(12,activation='relu'))
model1.add(Dense(8, activation='relu'))
model1.add(Dense(2, activation='sigmoid'))



In [0]:
# Compile model
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [125]:
# Fit the model
model1.fit(X_train, Y_train, validation_data=(X_test,Y_test), epochs=10, batch_size=5)

Train on 8000 samples, validate on 2000 samples
Epoch 1/10
8000/8000 [==============================] - 8s 974us/step - loss: 4.9323 - acc: 0.6931 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 2/10
8000/8000 [==============================] - 7s 893us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 3/10
8000/8000 [==============================] - 7s 923us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 4/10
8000/8000 [==============================] - 7s 912us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 5/10
8000/8000 [==============================] - 7s 937us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 6/10
8000/8000 [==============================] - 7s 936us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945
Epoch 7/10
8000/8000 [==============================] - 7s 903us/step - loss: 3.2581 - acc: 0.7968 - val_loss: 3.2942 - val_acc: 0.7945


In [126]:
model1.predict(X_test)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
y_predict=model1.predict_classes(X_test)

In [128]:
metrics.accuracy_score(y_test,y_predict)

0.7945

In [129]:
metrics.confusion_matrix(y_test,y_predict)

array([[1589,    0],
       [ 411,    0]])

In [130]:
cr=metrics.classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           0       0.79      1.00      0.89      1589
           1       0.00      0.00      0.00       411

    accuracy                           0.79      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.63      0.79      0.70      2000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


7. Optimize the model (Optional) Attempt 2

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [136]:
classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dropout(rate = 0.1))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

W0831 11:01:30.684987 139948103759744 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Epoch 1/100
8000/8000 [==============================] - 3s 421us/step - loss: 0.4865 - acc: 0.7967
Epoch 2/100
8000/8000 [==============================] - 3s 372us/step - loss: 0.4343 - acc: 0.7967
Epoch 3/100
8000/8000 [==============================] - 3s 369us/step - loss: 0.4343 - acc: 0.7967
Epoch 4/100
8000/8000 [==============================] - 3s 373us/step - loss: 0.4312 - acc: 0.7967
Epoch 5/100
8000/8000 [==============================] - 3s 379us/step - loss: 0.4282 - acc: 0.7967
Epoch 6/100
8000/8000 [==============================] - 3s 380us/step - loss: 0.4267 - acc: 0.8080
Epoch 7/100
8000/8000 [==============================] - 3s 372us/step - loss: 0.4259 - acc: 0.8246
Epoch 8/100
8000/8000 [==============================] - 3s 380us/step - loss: 0.4263 - acc: 0.8275
Epoch 9/100
8000/8000 [==============================] - 3s 384us/step - loss: 0.4254 - acc: 0.8271
Epoch 10/100
8000/8000 [==============================] - 3s 368us/step - loss: 0.4249 - acc: 0.8296

In [137]:
classifier.predict(X_test)

array([[0.07606888],
       [0.09763163],
       [0.08561406],
       ...,
       [0.12613079],
       [0.16522053],
       [0.30270338]], dtype=float32)

In [0]:
y_predict=classifier.predict_classes(X_test)

In [139]:
metrics.accuracy_score(y_test,y_predict)

0.833

In [140]:
metrics.confusion_matrix(y_test,y_predict)

array([[1538,   51],
       [ 283,  128]])

In [141]:
cr=metrics.classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.97      0.90      1589
           1       0.72      0.31      0.43       411

    accuracy                           0.83      2000
   macro avg       0.78      0.64      0.67      2000
weighted avg       0.82      0.83      0.81      2000

