### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [2]:
import tensorflow as tf
tf.reset_default_graph()
tf.set_random_seed(42)
import numpy as np
import pandas as pd
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


#### Collect Fashion mnist data from tf.keras.datasets 

In [3]:
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


#### Change train and test labels into one-hot vectors

In [0]:
ytrain = tf.keras.utils.to_categorical(ytrain, num_classes=10)
ytest = tf.keras.utils.to_categorical(ytest, num_classes=10)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))
model.add(tf.keras.layers.BatchNormalization())

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [7]:
#Hidden Layers
model.add(tf.keras.layers.Dense(200, activation='relu', name='Layer_1'))
model.add(tf.keras.layers.Dense(100, activation='relu', name='Layer_2'))

#Dropout Layers
model.add(tf.keras.layers.Dropout(0.5))

#Hidden layers
model.add(tf.keras.layers.Dense(60, activation='relu', name='Layer_3'))
model.add(tf.keras.layers.Dense(30, activation='relu', name='Layer_4'))

#Dropout layer
model.add(tf.keras.layers.Dropout(0.25))

W0824 08:00:23.927204 139887021684608 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
#Out Layer
model.add(tf.keras.layers.Dense(10, activation='softmax', name='Output'))

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 784)               0         
_________________________________________________________________
batch_normalization (BatchNo (None, 784)               3136      
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
Layer_3 (Dense)              (None, 60)                6060      
_________________________________________________________________
Layer_4 (Dense)              (None, 30)                1

In [11]:
#Graph Execution
model.fit(xtrain,ytrain,
          validation_data=(xtest, ytest),
          epochs= 30,
          batch_size=32)


Train on 60000 samples, validate on 10000 samples
Epoch 1/30
60000/60000 [==============================] - 11s 179us/sample - loss: 0.4930 - acc: 0.8589 - val_loss: 0.2498 - val_acc: 0.9525
Epoch 2/30
60000/60000 [==============================] - 10s 173us/sample - loss: 0.2301 - acc: 0.9404 - val_loss: 0.2375 - val_acc: 0.9624
Epoch 3/30
60000/60000 [==============================] - 10s 174us/sample - loss: 0.1751 - acc: 0.9546 - val_loss: 0.2109 - val_acc: 0.9673
Epoch 4/30
60000/60000 [==============================] - 10s 169us/sample - loss: 0.1418 - acc: 0.9639 - val_loss: 0.2024 - val_acc: 0.9687
Epoch 5/30
60000/60000 [==============================] - 10s 166us/sample - loss: 0.1212 - acc: 0.9683 - val_loss: 0.2137 - val_acc: 0.9701
Epoch 6/30
60000/60000 [==============================] - 10s 169us/sample - loss: 0.1116 - acc: 0.9715 - val_loss: 0.1950 - val_acc: 0.9702
Epoch 7/30
60000/60000 [==============================] - 11s 176us/sample - loss: 0.0990 - acc: 0.9739 

In [13]:
score=model.evaluate(xtest,ytest)

10000/10000 [==============================] - 1s 52us/sample - loss: 0.2558 - acc: 0.9737


In [14]:
score

[0.2558374306783423, 0.9737]

In [0]:
y_predict = model.predict(xtest)

In [16]:
y_predict[0]

array([6.3059870e-30, 7.5842833e-21, 3.5228848e-17, 2.2778537e-17,
       6.0460934e-14, 1.8329793e-21, 1.3510807e-35, 1.0000000e+00,
       2.1554739e-20, 8.0985685e-13], dtype=float32)

In [17]:
y_predict[0]

array([6.3059870e-30, 7.5842833e-21, 3.5228848e-17, 2.2778537e-17,
       6.0460934e-14, 1.8329793e-21, 1.3510807e-35, 1.0000000e+00,
       2.1554739e-20, 8.0985685e-13], dtype=float32)

In [18]:
np.argmax(y_predict[0])

7

In [20]:
test_y=[]
for val in ytest:
  test_y.append(np.argmax(val))
test_y[0]

7

In [21]:
y_pred = []
for val in y_predict:
    y_pred.append(np.argmax(val))

cm = metrics.confusion_matrix(test_y,y_pred)
print(cm)

[[ 971    1    0    1    0    3    2    1    0    1]
 [   1 1125    2    1    0    0    3    2    1    0]
 [   3    0 1002    5    2    0    2    8    8    2]
 [   0    0    6  988    0    4    1    3    4    4]
 [   1    1    3    1  953    2    4    4    3   10]
 [   2    0    0   11    1  867    4    1    5    1]
 [   5    4    2    1    4    6  931    0    5    0]
 [   2    2   10    4    3    1    2  988    3   13]
 [   0    1    5    4    3   14    2    3  937    5]
 [   2    2    0    7   12    5    0    3    3  975]]


In [23]:
cr=metrics.classification_report(test_y,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.97      0.97      0.97       982
           5       0.96      0.97      0.97       892
           6       0.98      0.97      0.98       958
           7       0.98      0.96      0.97      1028
           8       0.97      0.96      0.96       974
           9       0.96      0.97      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

