# Sentiment Classification


## Loading the dataset

In [1]:
from keras.datasets import imdb

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

Using TensorFlow backend.


17465344/17464789 [==============================] - 1s 0us/step


In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300  #number of word used from each review

## Train test split

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)

In [4]:
print ("x_train shape: ", x_train.shape)
print ("y_train shape: ", y_train.shape)
print ("x_test shape: ", x_test.shape)
print ("y_test shape: ", y_test.shape)

x_train shape:  (25000, 300)
y_train shape:  (25000,)
x_test shape:  (25000, 300)
y_test shape:  (25000,)


In [5]:
print("Maximum value of a word index ")
print(max([max(sequence) for sequence in x_train]))
print("Maximum length num words of review in train ")
print(max([len(sequence) for sequence in x_train]))

Maximum value of a word index 
9999
Maximum length num words of review in train 
300


3. Get the word index and then Create key value pair for word and word_id.

In [6]:
# Make Word to ID dictionary
INDEX_FROM=3   # word index offset
word_to_id = imdb.get_word_index() #Get the word index
word_to_id = {k:(v+INDEX_FROM) for k,v in word_to_id.items()}
word_to_id["[PAD]"] = 0
#word_to_id[""] = 0
word_to_id["[🏃]"] = 1 # START
word_to_id["[❓]"] = 2 # UNKNOWN

# Make ID to Word dictionary
id_to_word = {value:key for key,value in word_to_id.items()}

def restore_original_text(imdb_x_array):
    return (' '.join(id_to_word[id] for id in imdb_x_array ))

1646592/1641221 [==============================] - 0s 0us/step


In [7]:
id_to_word

{34704: 'fawn',
 52009: 'tsukino',
 52010: 'nunnery',
 16819: 'sonja',
 63954: 'vani',
 1411: 'woods',
 16118: 'spiders',
 2348: 'hanging',
 2292: 'woody',
 52011: 'trawling',
 52012: "hold's",
 11310: 'comically',
 40833: 'localized',
 30571: 'disobeying',
 52013: "'royale",
 40834: "harpo's",
 52014: 'canet',
 19316: 'aileen',
 52015: 'acurately',
 52016: "diplomat's",
 25245: 'rickman',
 6749: 'arranged',
 52017: 'rumbustious',
 52018: 'familiarness',
 52019: "spider'",
 68807: 'hahahah',
 52020: "wood'",
 40836: 'transvestism',
 34705: "hangin'",
 2341: 'bringing',
 40837: 'seamier',
 34706: 'wooded',
 52021: 'bravora',
 16820: 'grueling',
 1639: 'wooden',
 16821: 'wednesday',
 52022: "'prix",
 34707: 'altagracia',
 52023: 'circuitry',
 11588: 'crotch',
 57769: 'busybody',
 52024: "tart'n'tangy",
 14132: 'burgade',
 52026: 'thrace',
 11041: "tom's",
 52028: 'snuggles',
 29117: 'francesco',
 52030: 'complainers',
 52128: 'templarios',
 40838: '272',
 52031: '273',
 52133: 'zaniacs',

In [8]:
#Lets Decode and check for some train values.
x_train[10]

array([   6,  346,  137,   11,    4, 2768,  295,   36, 7740,  725,    6,
       3208,  273,   11,    4, 1513,   15, 1367,   35,  154,    2,  103,
          2,  173,    7,   12,   36,  515, 3547,   94, 2547, 1722,    5,
       3547,   36,  203,   30,  502,    8,  361,   12,    8,  989,  143,
          4, 1172, 3404,   10,   10,  328, 1236,    9,    6,   55,  221,
       2989,    5,  146,  165,  179,  770,   15,   50,  713,   53,  108,
        448,   23,   12,   17,  225,   38,   76, 4397,   18,  183,    8,
         81,   19,   12,   45, 1257,    8,  135,   15,    2,  166,    4,
        118,    7,   45,    2,   17,  466,   45,    2,    4,   22,  115,
        165,  764, 6075,    5, 1030,    8, 2973,   73,  469,  167, 2127,
          2, 1568,    6,   87,  841,   18,    4,   22,    4,  192,   15,
         91,    7,   12,  304,  273, 1004,    4, 1375, 1172, 2768,    2,
         15,    4,   22,  764,   55, 5773,    5,   14, 4233, 7444,    4,
       1375,  326,    7,    4, 4760, 1786,    8,  3

In [9]:
restore_original_text(x_train[10])

"a short while in the cell together they stumble upon a hiding place in the wall that contains an old [❓] after [❓] part of it they soon realise its magical powers and realise they may be able to use it to break through the prison walls br br black magic is a very interesting topic and i'm actually quite surprised that there aren't more films based on it as there's so much scope for things to do with it it's fair to say that [❓] makes the best of it's [❓] as despite it's [❓] the film never actually feels restrained and manages to flow well throughout director eric [❓] provides a great atmosphere for the film the fact that most of it takes place inside the central prison cell [❓] that the film feels very claustrophobic and this immensely benefits the central idea of the prisoners wanting to use magic to break out of the cell it's very easy to get behind them it's often said that the unknown is the thing that really [❓] people and this film proves that as the director [❓] that we can nev

In [10]:
#Lets Decode and check for some test values.
x_test[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [11]:
restore_original_text(x_test[0])

"[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PA

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [12]:
import tensorflow as tf
from tensorflow import keras
from keras import backend as K
import numpy as np
#from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional, GlobalAveragePooling1D

tf.set_random_seed(100)

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(64, activation='relu'))

# Dropout for regularization
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(32, activation="relu"))
model.add(keras.layers.Dense(16, activation="relu"))
model.add(keras.layers.Dense(1, activation="sigmoid"))

model.summary()

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          160000    
_________________________________________________________________
global_average_pooling1d (Gl (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 64)                1088      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                2080      
_______________________________________________________

In [13]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['acc'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [14]:
history = model.fit(x_train,
                    y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_test, y_test),
                    verbose=1)

Train on 25000 samples, validate on 25000 samples
Epoch 1/20
25000/25000 [==============================] - 2s 92us/sample - loss: 0.6920 - acc: 0.5418 - val_loss: 0.6865 - val_acc: 0.7429
Epoch 2/20
25000/25000 [==============================] - 1s 22us/sample - loss: 0.6386 - acc: 0.7288 - val_loss: 0.5407 - val_acc: 0.8034
Epoch 3/20
25000/25000 [==============================] - 1s 22us/sample - loss: 0.4116 - acc: 0.8458 - val_loss: 0.3311 - val_acc: 0.8650
Epoch 4/20
25000/25000 [==============================] - 1s 23us/sample - loss: 0.2745 - acc: 0.8947 - val_loss: 0.2946 - val_acc: 0.8798
Epoch 5/20
25000/25000 [==============================] - 1s 22us/sample - loss: 0.2224 - acc: 0.9190 - val_loss: 0.2898 - val_acc: 0.8810
Epoch 6/20
25000/25000 [==============================] - 1s 22us/sample - loss: 0.1901 - acc: 0.9349 - val_loss: 0.2937 - val_acc: 0.8828
Epoch 7/20
25000/25000 [==============================] - 1s 23us/sample - loss: 0.1641 - acc: 0.9466 - val_loss: 0.

In [15]:
print('\nModel Performance: Log Loss and Accuracy on train data')
print(model.evaluate(x_train, y_train, batch_size = 20))
print('\nModel Performance: Log Loss and Accuracy on validation data')
print(model.evaluate(x_test, y_test, batch_size = 20))


Model Performance: Log Loss and Accuracy on train data
25000/25000 [==============================] - 2s 72us/sample - loss: 0.0356 - acc: 0.9936
[0.03562223340459168, 0.99364]

Model Performance: Log Loss and Accuracy on validation data
25000/25000 [==============================] - 2s 76us/sample - loss: 0.5744 - acc: 0.8562
[0.5743877560857683, 0.85616]


In [16]:
'''
PREDICT
'''
import random
import pandas as pd

original_x_test = x_test

def restore_original_text(imdb_x_array):
    return (' '.join(id_to_word[id] for id in imdb_x_array ))

def imdb_class_to_str(imdb_class):
    if imdb_class == 0:
        return 'negative'
    return 'positive'

right = 0
mistake = 0

index_list = []
original_text_list = []
pred_prob_list = []
pred_class_list = []
y_test_list = []
fail_str_list = []

for i in range(100):
    index = random.randint(0, len(x_test))
    
    pred_prob = model.predict(x_test[index:(index+1)])[0][0] 
    pred_class = model.predict_classes(x_test[index:(index+1)])[0][0]
    
    '''
    print('pred_prod:', pred_prod)
    print('pred_class:', pred_class)
    print('y_test[index] :', y_test[index])
    '''
    fail_str = '' 
    
    if y_test[index] == pred_class:
        right += 1
    else:
        mistake += 1
        fail_str = 'Fail'
        
    original_text = restore_original_text(original_x_test[index])

    index_list.append(index)
    original_text_list.append(original_text)
    pred_prob_list.append(pred_prob)
    pred_class_list.append(imdb_class_to_str(pred_class))
    y_test_list.append(imdb_class_to_str(y_test[index]))
    fail_str_list.append(fail_str)

print("right : ", right)
print("mistake : ", mistake)
print("accuracy:", right/(right+mistake))

df = pd.DataFrame({'index': index_list, 
                   'x_test_original_text': original_text_list, 
                   'probability': pred_prob_list, 
                   'pred_class': pred_class_list,
                   'y_test': y_test_list,
                   'is_fail': fail_str_list
                  })

df[['index', 'x_test_original_text','probability','pred_class','y_test','is_fail']]

right :  86
mistake :  14
accuracy: 0.86


,index,x_test_original_text,probability,pred_class,y_test,is_fail
0,18593,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.001135,negative,negative,
1,3012,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.001422,negative,negative,
2,3180,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.000043,negative,negative,
3,10150,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.006880,negative,negative,
4,3528,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.000916,negative,negative,
...,...,...,...,...,...,...
95,19115,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.415368,negative,positive,Fail
96,19245,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.004200,negative,negative,
97,17164,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.000063,negative,negative,
98,21767,[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD...,0.001808,negative,negative,


## Retrive the output of each layer in keras for a given single test sample from the trained model you built

In [20]:
#Define function to get output of all the layers in the model for specific test input
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())

    def getLayerOutput(layer):
        get_Layer_Output = K.function([model.layers[0].input], [layer.output])
        return get_Layer_Output([x_test[0:1,]])[0]
    
    layer_output = []
    
    for layer in model.layers:
        layer_output.append(getLayerOutput(layer))

In [21]:
#Get the count of ouput. It should be equal to the number of layers
len(layer_output)

7

In [22]:

#Check all the outputs
layer_output

[array([[[-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         [-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         [-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         ...,
         [ 0.04579827, -0.00981784, -0.02570111, ...,  0.02962463,
          -0.04944974, -0.02211731],
         [ 0.04799093, -0.03852631,  0.04156684, ..., -0.01586529,
          -0.03594899,  0.03170117],
         [-0.00144356,  0.04378692,  0.00424818, ..., -0.01755618,
          -0.0028383 , -0.03627374]]], dtype=float32),
 array([[-0.00301607,  0.03692188,  0.01417997, -0.01547567, -0.01877829,
          0.0399677 , -0.0034747 , -0.01725606,  0.0074258 , -0.00178651,
          0.01001158, -0.00320485, -0.02594487,  0.0301198 , -0.01571364,
          0.00830047]], dtype=float32),
 array([[0.        , 0.        , 0.01101602, 0.00524644, 0.        ,
         0.  

In [23]:
#Get the specific layer output
layer_output[3]

array([[0.        , 0.        , 0.01101602, 0.00524644, 0.        ,
        0.        , 0.        , 0.01019217, 0.        , 0.        ,
        0.01768403, 0.01140995, 0.        , 0.00893559, 0.00641206,
        0.01021314, 0.        , 0.00821325, 0.        , 0.0034901 ,
        0.        , 0.        , 0.        , 0.02163267, 0.00107495,
        0.        , 0.02565341, 0.02123948, 0.02182533, 0.00820519,
        0.00686321, 0.00561919, 0.        , 0.        , 0.        ,
        0.0016309 , 0.        , 0.        , 0.00802844, 0.        ,
        0.00860214, 0.        , 0.0046777 , 0.011356  , 0.02129352,
        0.01169974, 0.00418537, 0.        , 0.        , 0.00566915,
        0.        , 0.00548731, 0.00245883, 0.00457622, 0.00041493,
        0.01304827, 0.01613861, 0.00882609, 0.        , 0.        ,
        0.00266701, 0.        , 0.00302794, 0.00224574]], dtype=float32)